### ISSUE TITLE
Media 3 Exoplayer bug fix (Android 14 / API 34)

### ISSUE THREAD

**Issue by ryanw-mobile** [ryanw-mobile/dazn-code-challenge#44]
We should have got most of the PIP implementation right, but we'd better follow the official doc for every minor step to make sure the implementation is right and stick to the recommendations.

On Pixel 7 the player looks to scale the video 1:1 then crop 50% vertically. That's a sign shown when we disabled the control display.

**Comment by ryanw-mobile** [comment]
Exact issue:
https://github.com/androidx/media/issues/1270

Which seems to be related to the calculated video width & height does not match the actual one.

**Comment by ryanw-mobile** [comment]
Emulator: Pixel 7 - API 33 - Correct Output

Sequence: `ZOOM`, `FIXED_WIDTH`, `FIXED_HEIGHT`, `FIT`, `FILL`

![API33_RESIZE_MODE_ZOOM](https://github.com/ryanw-mobile/dazn-code-challenge/assets/22452240/f6d98e05-293b-4c38-b64e-cc6f35736d35) ![API33_RESIZE_MODE_FIXED_WIDTH](https://github.com/ryanw-mobile/dazn-code-challenge/assets/22452240/1aeef778-4b89-4fc8-861c-98eadb403122) ![API33_RESIZE_MODE_FIXED_HEIGHT](https://github.com/ryanw-mobile/dazn-code-challenge/assets/22452240/b97684ce-3a18-4ef6-9920-51e5040b004b) ![API33_RESIZE_MODE_FIT](https://github.com/ryanw-mobile/dazn-code-challenge/assets/22452240/aa381131-3e93-42f8-b14f-60b62f4af460) ![API33_RESIZE_MODE_FILL](https://github.com/ryanw-mobile/dazn-code-challenge/assets/22452240/1e3d4481-dc3c-4b24-ba9b-612a75d9eefc)


Emulator: Pixel 7 - API 34 - Distorted Output

![API34_RESIZE_MODE_ZOOM](https://github.com/ryanw-mobile/dazn-code-challenge/assets/22452240/9ff11efc-8927-485b-8df5-f91a1000354f) ![API34_RESIZE_MODE_FIXED_WIDTH](https://github.com/ryanw-mobile/dazn-code-challenge/assets/22452240/3af3e6f1-ac7a-422c-811a-a817dfbca9bc) ![API34_RESIZE_MODE_FIXED_HEIGHT](https://github.com/ryanw-mobile/dazn-code-challenge/assets/22452240/cb3cb10c-375a-4ffb-bd40-764a05d04d32) ![API34_RESIZE_MODE_FIT](https://github.com/ryanw-mobile/dazn-code-challenge/assets/22452240/5306be87-10a5-44dc-a224-b345ce6faa5a) ![API34_RESIZE_MODE_FILL](https://github.com/ryanw-mobile/dazn-code-challenge/assets/22452240/34980d6a-7a85-4701-9ee1-33b2004ac33c)


Emulator: Pixel 7 - VanillaIceCream

![V_RESIZE_MODE_ZOOM](https://github.com/ryanw-mobile/dazn-code-challenge/assets/22452240/0400b904-69fe-4af2-9883-ee0bb2ff66f5) ![V_RESIZE_MODE_FIXED_WIDTH](https://github.com/ryanw-mobile/dazn-code-challenge/assets/22452240/a36d65bb-042e-4137-b70e-290084543aa7) ![V_RESIZE_MODE_FIXED_HEIGHT](https://github.com/ryanw-mobile/dazn-code-challenge/assets/22452240/e858da9a-b39d-401d-8182-638daaf0cb99) ![V_RESIZE_MODE_FIT](https://github.com/ryanw-mobile/dazn-code-challenge/assets/22452240/9004d239-3012-4d47-9224-df0801063b6a) ![V_RESIZE_MODE_FILL](https://github.com/ryanw-mobile/dazn-code-challenge/assets/22452240/fcaf099c-d835-4ac5-9aec-0aa1a13577e9)

**Comment by fresnohernandez99** [comment]
facing same issue here

**Comment by ryanw-mobile** [comment]
> facing same issue here

I could see the player worked a few times by only keeping the basic code to set up the player. However, the result was inconsistent and sometimes did not work. I tried to forcefully invalidate the view (because, obviously, it is due to the player getting the wrong screen dimensions) but could not fix it. 

As I mentioned in the Google's issue ticket - since the same piece of code and the library worked on previous Android versions, it can be difficult to say our code / the exoplayer has a bug. If that's due to OS changes, it can be difficult for us to fix/diagnose. 

Right now, I can only leave this issue open.

**Comment by fresnohernandez99** [comment]
For me it work with a condition. If i'll use RESIZE_MODE_FIXED_WIDTH for example i have to set the container with fillMaxWidth() and not fillMaxSize()

**Comment by RyeGordo** [comment]
I'm having the same issue with stretched video, but for me it seems like `resizeMode` is ignored as there is no change in behaviour.

**Comment by ryanw-mobile** [comment]
> I'm having the same issue with stretched video; additionally, for me it seems like `resizeMode` is ignored as there is no change in behaviour.

For this code base, I have been able to confirm two findings:
1. It is running fine on API 33. The same piece of code doesn't work on API 34+ - so it is debatable to say my code is incorrect.
2. I have set the controller to hide when the player starts. When I tap on the player to show the controller, the video resizes properly automatically. This looks to me like the player did not have the correct screen size to start with, and later when it had to invalidate the layout (and get the screen size again), it worked properly as it got the correct screen size for scaling.

Therefore, I believe something is wrong when the player tries to get/calculate the view's screen size on API 34+. If there is a bug, it might be a compose/ other OS bug rather than the exoplayer library's since, again, the same player works well on API 33. This makes it difficult to investigate further.

Another possibility might be due to my complex activity setup—I use Single Activity to implement the player and PIP, so it might be my fault for accidentally overriding some configuration changes. I plan to comment on all other extra features in my project to see if the player would work again.

**Comment by ryanw-mobile** [comment]
Tested again by elevating media3 to 1.4.0-alpha02. As expected, this does not solve the problem.

**Comment by ryanw-mobile** [comment]
We are getting closer to the root cause (that Google has yet face the reality):
[AspectRatioFrameLayout problem ](https://github.com/androidx/media/issues/1237)
"there seems to be another cause of the issue that was introduced on the 5th, March 2024, that is somehow correlated to hardware acceleration, Jetpack Compose, and Google Pixel phones."

[Video is cut on the edge when using Compose and uses RESIZE_MODE_ZOOM - Only Android 14](https://github.com/androidx/media/issues/1123#top)

**Comment by ryanw-mobile** [comment]
Root cause identified. The workaround will be available in [media3](https://developer.android.com/jetpack/androidx/releases/media3) `1.4.0-rc01` .

We don't have access to `SurfaceSyncGroupCompatV34`, so we cannot apply locally a patched [`PlayerView.java`](https://github.com/androidx/media/commit/968f72fec6d5452a34976824ac822782eeeb8f45#diff-c7b6318135966f6ca6538387ea348f541c108800ccacd4ed13806df3cae9d525), so it's better to wait until `1.4.0-rc01` is available.

https://github.com/androidx/media/issues/1237#issuecomment-2168399603

> I've updated the title of this issue to reflect that this isn't specific to AspectRatioFrameLayout, and it's more related to SurfaceView inside a Compose AndroidView on Android 14.
>
> With the support of the graphics team, I've also submitted a workaround (linked above) to PlayerView, which resolves this issue for users of this class. This will be included in 1.4.0-rc01. I'm going to close this issue, since that should resolve the issue for users of media3's UI components. Those who have written their own UI components may be able to adopt a similar workaround.

**Comment by RyeGordo** [comment]
I'm glad you found the issue and look forward to this workaround.

Thanks for your efforts regarding this.

**Comment by RyeGordo** [comment]
The update to `1.4.0-rc01` did not seem to fix my scaling issues; however, I noticed that my `videoScalingMode` was set to `VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING`.  Changing it to `VIDEO_SCALING_MODE_SCALE_TO_FIT` seems to fix my scaling issue.

**Comment by ryanw-mobile** [comment]
> The update to `1.4.0-rc01` did not seem to fix my scaling issues; however, I noticed that my `videoScalingMode` was set to `VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING`. Changing it to `VIDEO_SCALING_MODE_SCALE_TO_FIT` seems to fix my scaling issue.

But you still need `1.4.0-rc01` with `VIDEO_SCALING_MODE_SCALE_TO_FIT` to make it work, right?

**Comment by RyeGordo** [comment]
Setting `VIDEO_SCALING_MODE_SCALE_TO_FIT` while remaining on the previous `1.3.1` version fixes my issue.
The `1.4.0-rc01` does not seem to have any impact.

**Comment by ryanw-mobile** [comment]
> Same here. I have the same issue with the version `1.4.0-rc01` than with `1.3.1`. I don't see this problem on the physical Samsung device I have, but as soon I am running it on the emulator with Pixel 7 or Pixel 8, with Android 14, some black band will appear on the right side and the bottom of the video.
> 
> Btw, this problem happens only with 2 of the sample video I am working with. It does not happen with a third video with better quality. Maybe it is because the video couldn't stretch to the whole screen?
> 
> I am wrapping the player over a vertical view pager. Another interesting finding is that while the video of the first page works fine, when I scroll down and scroll up (go to another video and go back to it again), the same video will resize and shrink.

Thank you for your sharing. 

However, this is not a place to report any issues if you believe the root cause is different.  I would suggest you report it back to Google for your case.
